# -*- coding: utf-8 -*-
"""ml_model_registry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JapnSuIm06XEDUiCuKEH0xmlKpyslWx

# **Registro de Modelos de Machine Learning**
"""
import mlflow
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, precision_score, recall_score, roc_curve, auc

"""# 1. Cargue del daraset load_wine() de Sklearn"""
mlflow.set_tracking_uri("http://127.0.0.1:5000")

# Cargue del dataset

data = load_wine()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

print('Dataset dimentions: ', df.shape)
df.head()

"""# 2. División de datos de entrenamiento y prueba"""

# Division de los datos de entrenamiento y prueba
X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=42, stratify=y)

print(f"Training size: {X_train.shape}, Testing size: {X_test.shape}")

print(X_train.head())
print(y_train.head())

"""# 3. Creación del Pipeline"""

import mlflow
import mlflow.sklearn

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', LogisticRegression(max_iter=1000, C=0.5, penalty='l2', solver='lbfgs'))
])

experiment = mlflow.set_experiment(experiment_name="Wine experiment number one")
with mlflow.start_run(experiment_id=experiment.experiment_id):
  pipe.fit(X_train, y_train)
  y_pred = pipe.predict(X_test)

  y_pred = pipe.predict(X_test)

  acc = accuracy_score(y_test, y_pred)
  prec = precision_score(y_test, y_pred, average='weighted')
  rec = recall_score(y_test, y_pred, average='weighted')
  f1 = f1_score(y_test, y_pred, average='weighted')

  print(f"Accuracy: {acc:.2f}")
  print(f"Precision: {prec:.2f}")
  print(f"Recall: {rec:.2f}")
  print(f"F1 Score: {f1:.2f}")

  cm = confusion_matrix(y_test, y_pred)
  print("Confusion Matrix:")
  print(cm)

  mlflow.log_param("max_iter", pipe["classifier"].max_iter)
  mlflow.log_param("c", pipe["classifier"].C)
  mlflow.log_param("penalty", pipe["classifier"].penalty)
  mlflow.log_param("solver", pipe["classifier"].solver)



  mlflow.log_metric("accuracy", acc)
  mlflow.log_metric("precision", prec)
  mlflow.log_metric("recall", rec)
  mlflow.log_metric("f1_score", f1)

  #mlflow.sklearn.log_model() para guardar el modelo
  mlflow.sklearn.log_model(pipe, "wine_model", registered_model_name="wine_model")

"""# 4. Evaluación del modelo de Regresión Logistica

# 5. Guardar modelo entrenado
"""

import joblib
import os

model_dir = "model"
if not os.path.exists(model_dir):
  os.makedirs(model_dir)

model_path = os.path.join(model_dir, "logistic_regression_model.pkl")
joblib.dump(pipe, model_path)

print(f"Model save succesfully at the path: {model_path}")
print(f"Tamaño del archivo: {os.path.getsize(model_path)} bytes.")

"""# 6. Cargar del modelo guardado"""

model_path = os.path.join("model", "logistic_regression_model.pkl")

if os.path.exists(model_path):
  loaded_pipeline = joblib.load(model_path)
  print(f"Model loaded succesfully from: {model_path}")

  print("Pipeline components:")
  for step_name, step_object in loaded_pipeline.steps:
    print(f" - {step_name}: {type(step_object).__name__}")
else:
  print(f"Error: Model not found at: {model_path}")
  print("Make sure to execute the save model step.")

"""# 7. Probar el modelo con datos"""

# Hacer predicciones con el modelo cargado
y_pred_loaded = loaded_pipeline.predict(X_test)
y_pred_proba_loaded = loaded_pipeline.predict_proba(X_test)

# Evaluar el modelo cargado
acc_loaded = accuracy_score(y_test, y_pred_loaded)
prec_loaded = precision_score(y_test, y_pred_loaded, average='weighted')
recall_loaded = recall_score(y_test, y_pred_loaded, average='weighted')
f1_loaded = f1_score(y_test, y_pred_loaded, average='weighted')

print("=== Resultados del modelo cargado ===")
print(f"Accuracy: {acc_loaded:.4f}")
print(f"Precision: {prec_loaded:.4f}")
print(f"Recall: {recall_loaded:.4f}")
print(f"F1 Score: {f1_loaded:.4f}")

# Verificar que las predicciones son idénticas al modelo original
predicciones_identicas = np.array_equal(y_pred, y_pred_loaded)
print(f"\n¿Las predicciones son idénticas al modelo original? {predicciones_identicas}")

"""# 8. Promotion from 'None' -> 'Staging' -> 'Production'"""

from mlflow.tracking import MlflowClient

client = MlflowClient()

model_name = "wine_model"
latest_version = client.get_latest_versions(model_name, stages=["None"])[0].version

client.transition_model_version_stage(
    name=model_name,
    version=latest_version,
    stage="Staging"
)

client.transition_model_version_stage(
    name=model_name,
    version=latest_version,
    stage="Production"
)

"""#"""